
u1 = User.create(username:"willsinn", password:"willsinn", bio:"William Howard Sinn, NYC NY", avatar: "https://png.pngtree.com/svg/20170308/508749a69e.svg")

u2 = User.create(username:"camille", password:"camille", bio:"Camille San Miguel, Maryland", avatar: "https://www.w3schools.com/howto/img_avatar2.png")

s1 = Search.create(company: "greyhound", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-11")

s2 = Search.create(company: "greyhound", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-12")

s3 = Search.create(company: "megabus", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-12")

s4 = Search.create(company: "megabus", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-11")

s5 = Search.create(company: "greyhound", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-11")

s6 = Search.create(company: "greyhound", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-12")

s7 = Search.create(company: "megabus", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-12")

s8 = Search.create(company: "megabus", start_from: "NY, NY", to_destination: "Maryland", date: "2019-7-11")


u1s1i1 = Item.create(search_id: 1, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i2 = Item.create(search_id: 1, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i3 = Item.create(search_id: 1, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i4 = Item.create(search_id: 1, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i5 = Item.create(search_id: 1, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i6 = Item.create(search_id: 1, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i7 = Item.create(search_id: 1, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i8 = Item.create(search_id: 1, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i9 = Item.create(search_id: 1, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i10 = Item.create(search_id: 1, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i11 = Item.create(search_id: 1, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i12 = Item.create(search_id: 1, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i13 = Item.create(search_id: 1, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i14 = Item.create(search_id: 1, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i15 = Item.create(search_id: 1, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i16 = Item.create(search_id: 1, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i17 = Item.create(search_id: 1, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i18 = Item.create(search_id: 1, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i19 = Item.create(search_id: 1, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i20 = Item.create(search_id: 1, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i21 = Item.create(search_id: 1, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i22 = Item.create(search_id: 1, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i23 = Item.create(search_id: 1, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s1i24 = Item.create(search_id: 1, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")

u1s2i1 = Item.create(search_id: 2, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i2 = Item.create(search_id: 2, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i3 = Item.create(search_id: 2, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i4 = Item.create(search_id: 2, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i5 = Item.create(search_id: 2, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i6 = Item.create(search_id: 2, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i7 = Item.create(search_id: 2, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i8 = Item.create(search_id: 2, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i9 = Item.create(search_id: 2, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i10 = Item.create(search_id: 2, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i11 = Item.create(search_id: 2, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i12 = Item.create(search_id: 2, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i13 = Item.create(search_id: 2, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i14 = Item.create(search_id: 2, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i15 = Item.create(search_id: 2, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i16 = Item.create(search_id: 2, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i17 = Item.create(search_id: 2, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i18 = Item.create(search_id: 2, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i19 = Item.create(search_id: 2, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i20 = Item.create(search_id: 2, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i21 = Item.create(search_id: 2, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i22 = Item.create(search_id: 2, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i23 = Item.create(search_id: 2, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s2i24 = Item.create(search_id: 2, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")

u1s3i1 = Item.create(search_id: 3, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i2 = Item.create(search_id: 3, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i3 = Item.create(search_id: 3, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i4 = Item.create(search_id: 3, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i5 = Item.create(search_id: 3, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i6 = Item.create(search_id: 3, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i7 = Item.create(search_id: 3, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i8 = Item.create(search_id: 3, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i9 = Item.create(search_id: 3, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i10 = Item.create(search_id: 3, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i11 = Item.create(search_id: 3, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i12 = Item.create(search_id: 3, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i13 = Item.create(search_id: 3, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i14 = Item.create(search_id: 3, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i15 = Item.create(search_id: 3, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i16 = Item.create(search_id: 3, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i17 = Item.create(search_id: 3, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i18 = Item.create(search_id: 3, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i19 = Item.create(search_id: 3, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i20 = Item.create(search_id: 3, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i21 = Item.create(search_id: 3, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i22 = Item.create(search_id: 3, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i23 = Item.create(search_id: 3, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s3i24 = Item.create(search_id: 3, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")


u1s4i1 = Item.create(search_id: 4, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i2 = Item.create(search_id: 4, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i3 = Item.create(search_id: 4, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i4 = Item.create(search_id: 4, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i5 = Item.create(search_id: 4, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i6 = Item.create(search_id: 4, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i7 = Item.create(search_id: 4, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i8 = Item.create(search_id: 4, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i9 = Item.create(search_id: 4, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i10 = Item.create(search_id: 4, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i11 = Item.create(search_id: 4, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i12 = Item.create(search_id: 4, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i13 = Item.create(search_id: 4, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i14 = Item.create(search_id: 4, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i15 = Item.create(search_id: 4, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i16 = Item.create(search_id: 4, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i17 = Item.create(search_id: 4, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i18 = Item.create(search_id: 4, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i19 = Item.create(search_id: 4, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i20 = Item.create(search_id: 4, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i21 = Item.create(search_id: 4, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i22 = Item.create(search_id: 4, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i23 = Item.create(search_id: 4, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u1s4i24 = Item.create(search_id: 4, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")


u2s1i1 = Item.create(search_id: 5, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i2 = Item.create(search_id: 5, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i3 = Item.create(search_id: 5, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i4 = Item.create(search_id: 5, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i5 = Item.create(search_id: 5, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i6 = Item.create(search_id: 5, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i7 = Item.create(search_id: 5, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i8 = Item.create(search_id: 5, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i9 = Item.create(search_id: 5, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i10 = Item.create(search_id: 5, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i11 = Item.create(search_id: 5, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i12 = Item.create(search_id: 5, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i13 = Item.create(search_id: 5, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i14 = Item.create(search_id: 5, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i15 = Item.create(search_id: 5, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i16 = Item.create(search_id: 5, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i17 = Item.create(search_id: 5, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i18 = Item.create(search_id: 5, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i19 = Item.create(search_id: 5, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i20 = Item.create(search_id: 5, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i21 = Item.create(search_id: 5, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i22 = Item.create(search_id: 5, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i23 = Item.create(search_id: 5, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s1i24 = Item.create(search_id: 5, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")


u2s2i1 = Item.create(search_id: 6, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i2 = Item.create(search_id: 6, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i3 = Item.create(search_id: 6, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i4 = Item.create(search_id: 6, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i5 = Item.create(search_id: 6, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i6 = Item.create(search_id: 6, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i7 = Item.create(search_id: 6, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i8 = Item.create(search_id: 6, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i9 = Item.create(search_id: 6, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i10 = Item.create(search_id: 6, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i11 = Item.create(search_id: 6, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i12 = Item.create(search_id: 6, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i13 = Item.create(search_id: 6, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i14 = Item.create(search_id: 6, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i15 = Item.create(search_id: 6, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i16 = Item.create(search_id: 6, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i17 = Item.create(search_id: 6, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i18 = Item.create(search_id: 6, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i19 = Item.create(search_id: 6, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i20 = Item.create(search_id: 6, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i21 = Item.create(search_id: 6, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i22 = Item.create(search_id: 6, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i23 = Item.create(search_id: 6, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s2i24 = Item.create(search_id: 6, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")


u2s3i1 = Item.create(search_id: 7, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i2 = Item.create(search_id: 7, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i3 = Item.create(search_id: 7, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i4 = Item.create(search_id: 7, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i5 = Item.create(search_id: 7, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i6 = Item.create(search_id: 7, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i7 = Item.create(search_id: 7, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i8 = Item.create(search_id: 7, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i9 = Item.create(search_id: 7, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i10 = Item.create(search_id: 7, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i11 = Item.create(search_id: 7, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i12 = Item.create(search_id: 7, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i13 = Item.create(search_id: 7, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i14 = Item.create(search_id: 7, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i15 = Item.create(search_id: 7, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i16 = Item.create(search_id: 7, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i17 = Item.create(search_id: 7, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i18 = Item.create(search_id: 7, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i19 = Item.create(search_id: 7, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i20 = Item.create(search_id: 7, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i21 = Item.create(search_id: 7, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i22 = Item.create(search_id: 7, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i23 = Item.create(search_id: 7, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s3i24 = Item.create(search_id: 7, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")


u2s4i1 = Item.create(search_id: 8, price: "11", time: "01:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i2 = Item.create(search_id: 8, price: "22", time: "02:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i3 = Item.create(search_id: 8, price: "33", time: "03:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i4 = Item.create(search_id: 8, price: "44", time: "04:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i5 = Item.create(search_id: 8, price: "55", time: "05:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i6 = Item.create(search_id: 8, price: "66", time: "06:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i7 = Item.create(search_id: 8, price: "77", time: "07:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i8 = Item.create(search_id: 8, price: "11", time: "08:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i9 = Item.create(search_id: 8, price: "12", time: "09:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i10 = Item.create(search_id: 8, price: "31", time: "10:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i11 = Item.create(search_id: 8, price: "41", time: "11:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i12 = Item.create(search_id: 8, price: "51", time: "12:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i13 = Item.create(search_id: 8, price: "16", time: "13:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i14 = Item.create(search_id: 8, price: "71", time: "14:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i15 = Item.create(search_id: 8, price: "12", time: "15:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i16 = Item.create(search_id: 8, price: "22", time: "16:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i17 = Item.create(search_id: 8, price: "32", time: "17:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i18 = Item.create(search_id: 8, price: "42", time: "18:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i19 = Item.create(search_id: 8, price: "52", time: "19:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i20 = Item.create(search_id: 8, price: "62", time: "20:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i21 = Item.create(search_id: 8, price: "72", time: "21:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i22 = Item.create(search_id: 8, price: "23", time: "22:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i23 = Item.create(search_id: 8, price: "12", time: "23:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
u2s4i24 = Item.create(search_id: 8, price: "19", time: "24:00", pickup_from: "Manhattan, NY, Port Authority", purchase_url: "https://www.greyhound.com/en")
